### ISSUE TITLE
Hello, buddy! Some issue need help.

### ISSUE THREAD

**Issue by ghost** [leftstick/jekyll-materiallize#1]
First of all, your theme is very nice.
I also find a [materialize theme](https://github.com/naveenshaji/material). 
We can improve your theme together~

I'm an android developer without any web development experience.
I've made a jekyll blog but it have some [issue](http://www.johnwatsondev.com/Say-Hello-To-Everybody/). 

I'll be appreciate it if you can contact with me. Please find me through my [blog](http://www.johnwatsondev.com).
Best Regards~

**Comment by leftstick** [comment]
I've just sent an PR, Give a try. Feel free to put question here

**Comment by ghost** [comment]
Thx vm, brother~
