### ISSUE TITLE
xml、html 代码的预览很难看

### ISSUE THREAD

**Issue by loshine** [leftstick/jekyll-materiallize#2]
## html

![code](https://cloud.githubusercontent.com/assets/11252444/9900371/e3e22f52-5c92-11e5-875c-f49a677937f3.png)
## java

![code2](https://cloud.githubusercontent.com/assets/11252444/9900413/372e28d2-5c93-11e5-90bc-3f08bbf29e88.png)

如图所示，与其它语言的预览完全不一致，希望能够改进。

**Comment by leftstick** [comment]
`html` 和`xml`是支持的，在代码内置的代码高亮系统里，统一用`markup`表示，代码可以这样写
![snip20150916_1](https://cloud.githubusercontent.com/assets/1059956/9901318/853a6922-5c99-11e5-8083-aad90f5e7226.png)

**Comment by loshine** [comment]
感谢，这个问题已经解决了，看起来很棒~

但是现在出现了另一个问题，在文章中点击这样的超链接

![3](https://cloud.githubusercontent.com/assets/11252444/9923266/77e83970-5d25-11e5-810c-4d764aebc876.png)

它直接链接到了主页

![2](https://cloud.githubusercontent.com/assets/11252444/9923270/8294e8a0-5d25-11e5-89e9-5444e1212cc7.png)

这是markdown

![1](https://cloud.githubusercontent.com/assets/11252444/9923273/8882c390-5d25-11e5-84d1-88031665306a.png)

请问一下如何解决。。

**Comment by leftstick** [comment]
你的`markdown`写的没问题，是我这边的bug，我没把`html`的`base`处理好，已经修正了，你可以通过如下命令拉去fix:

``` bash
#增加remote upstream url到我的repo
git remote add upstream https://github.com/leftstick/jekyll-materiallize.git
#把我的fix拉取到本地的upstream/master分支
git fetch upstream
#切换到你本地的工作分支，譬如：master
git checkout master
#合并我的fix到你的本地分支
git merge upstream/master
```

然后你的锚点应该可以工作了

**Comment by loshine** [comment]
如您所述操作之后发现描点可以正常工作了，但是此时使用描点会刷新整个页面

观察发现与其它的地方相比最后多了一个`/`

本主题下的描点链接是
`http://www.xxxx.html#point`
但是点击之后在地址栏显示的是
`http://www.xxxx.html/#point`

正常情况下应该是
`http://www.xxxx.html#point`
其它网站的页面如果使用
`http://www.xxxx.html/#point`
是无法跳转的

因为对jekyll仅限于会使用而不知道该如何修改，所以只能麻烦您了

**Comment by leftstick** [comment]
这还是因为`html`里的`base`属性问题，貌似只要设置了`base`，他就一定会重刷页面(没找理论依据)。

我现在的做法是，只要你的`_config.yml`配置文件里给`BASE_PATH`赋值成`false`，我就去掉页面中的`base` tag。

去掉`base`tag后，你的锚点就可以正常工作，而且不会刷新页面了

**Comment by loshine** [comment]
非常感谢，已经用上了噢 😄
